-- 004: Actions table for Action Plan & Tracker (Sprint 3)
-- Stores actionable next steps generated by AI Navigator or created manually

create table public.actions (
  id uuid primary key default gen_random_uuid(),
  family_id uuid references public.families(id) on delete cascade not null,
  child_id uuid references public.children(id) on delete set null,
  chat_session_id uuid references public.chat_sessions(id) on delete set null,

  -- Core fields
  title text not null,
  description text,
  category text not null default 'general',
    -- 'regional_center', 'iep', 'insurance', 'benefits', 'medical', 'legal', 'general'
  priority text not null default 'medium',
    -- 'urgent', 'high', 'medium', 'low'

  -- Status management (4 states per Sprint 3 spec)
  status text not null default 'not_started'
    check (status in ('not_started', 'in_progress', 'completed', 'dismissed')),

  -- Scripts / guidance
  script text,           -- Pre-written script (e.g., "call your RC and say...")
  steps jsonb,           -- Ordered checklist: [{step: "...", done: bool}]
  kb_article_ids text[], -- Links to relevant KB articles (e.g., ['RC-001', 'RC-003'])

  -- Timelines
  due_date date,
  deadline_warning_days integer default 7,
  completed_at timestamptz,
  dismissed_at timestamptz,
  dismissed_reason text,

  -- Source tracking
  source text not null default 'manual',
    -- 'ai_navigator' (saved from chat), 'manual' (user-created), 'system' (auto-generated)
  source_message_id uuid, -- If saved from chat, the specific message ID

  -- Follow-up
  follow_up_date date,
  follow_up_note text,
  reminder_sent boolean default false,

  -- Offline sync
  local_id text,           -- Client-side ID for offline-created actions
  synced_at timestamptz,   -- Last successful sync timestamp
  version integer default 1, -- Optimistic concurrency control

  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Indexes
create index idx_actions_family_id on public.actions(family_id);
create index idx_actions_child_id on public.actions(child_id);
create index idx_actions_status on public.actions(status);
create index idx_actions_due_date on public.actions(due_date);
create index idx_actions_category on public.actions(category);
create index idx_actions_local_id on public.actions(local_id) where local_id is not null;

-- Updated_at trigger
create trigger set_updated_at before update on public.actions
  for each row execute function public.handle_updated_at();

-- RLS policies (matches pattern from 002)
alter table public.actions enable row level security;

create policy "Users can manage their own actions"
  on public.actions for all
  using (family_id in (select id from public.families where user_id = auth.uid()))
  with check (family_id in (select id from public.families where user_id = auth.uid()));

-- Analytics view: action completion stats per family
create or replace view public.action_stats as
select
  family_id,
  count(*) as total_actions,
  count(*) filter (where status = 'completed') as completed_count,
  count(*) filter (where status = 'in_progress') as in_progress_count,
  count(*) filter (where status = 'not_started') as not_started_count,
  count(*) filter (where status = 'dismissed') as dismissed_count,
  round(
    count(*) filter (where status = 'completed')::numeric
    / nullif(count(*) filter (where status != 'dismissed'), 0) * 100,
    1
  ) as completion_rate,
  avg(
    extract(epoch from (completed_at - created_at)) / 86400
  ) filter (where status = 'completed') as avg_days_to_complete
from public.actions
group by family_id;
-- Phase 1: Google Calendar sync columns
-- Tracks the Google Calendar event ID for bi-directional sync

ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS google_calendar_event_id TEXT;

ALTER TABLE deadlines
  ADD COLUMN IF NOT EXISTS google_calendar_event_id TEXT;

-- Index for efficient sync lookups
CREATE INDEX IF NOT EXISTS idx_appointments_gcal_id
  ON appointments (google_calendar_event_id)
  WHERE google_calendar_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_deadlines_gcal_id
  ON deadlines (google_calendar_event_id)
  WHERE google_calendar_event_id IS NOT NULL;
-- Phase 5: Community Forum schema
-- Categories, threads, posts, reactions, reports, and direct messages

-- ─── Forum Categories ───────────────────────────────────────────────────────
create table public.forum_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  emoji text default '💬',
  sort_order integer default 0,
  is_diagnosis_specific boolean default false,
  thread_count integer default 0,
  created_at timestamptz default now() not null
);

-- ─── Forum Threads ──────────────────────────────────────────────────────────
create table public.forum_threads (
  id uuid primary key default gen_random_uuid(),
  category_id uuid references public.forum_categories(id) on delete cascade not null,
  author_id uuid references auth.users(id) on delete cascade not null,
  author_display_name text not null,
  title text not null,
  body text not null,
  tags text[] default '{}',
  is_pinned boolean default false,
  is_locked boolean default false,
  is_hidden boolean default false,
  post_count integer default 0,
  last_post_at timestamptz default now(),
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- ─── Forum Posts (replies) ──────────────────────────────────────────────────
create table public.forum_posts (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid references public.forum_threads(id) on delete cascade not null,
  parent_post_id uuid references public.forum_posts(id) on delete cascade,
  author_id uuid references auth.users(id) on delete cascade not null,
  author_display_name text not null,
  body text not null,
  is_hidden boolean default false,
  reaction_count integer default 0,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- ─── Reactions ──────────────────────────────────────────────────────────────
create table public.forum_reactions (
  id uuid primary key default gen_random_uuid(),
  post_id uuid references public.forum_posts(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  reaction text not null, -- '👍', '👏', '❤️'
  created_at timestamptz default now() not null,
  unique (post_id, user_id, reaction)
);

-- ─── Reports ────────────────────────────────────────────────────────────────
create table public.forum_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid references auth.users(id) on delete cascade not null,
  thread_id uuid references public.forum_threads(id) on delete cascade,
  post_id uuid references public.forum_posts(id) on delete cascade,
  reason text not null,
  status text default 'pending', -- 'pending', 'reviewed', 'actioned', 'dismissed'
  moderator_notes text,
  created_at timestamptz default now() not null,
  resolved_at timestamptz
);

-- ─── Direct Messages ────────────────────────────────────────────────────────
create table public.direct_messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid references auth.users(id) on delete cascade not null,
  recipient_id uuid references auth.users(id) on delete cascade not null,
  body text not null,
  is_read boolean default false,
  created_at timestamptz default now() not null
);

-- ─── User Blocks ────────────────────────────────────────────────────────────
create table public.user_blocks (
  id uuid primary key default gen_random_uuid(),
  blocker_id uuid references auth.users(id) on delete cascade not null,
  blocked_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamptz default now() not null,
  unique (blocker_id, blocked_id)
);

-- ─── Indexes ────────────────────────────────────────────────────────────────
create index idx_threads_category on public.forum_threads(category_id);
create index idx_threads_author on public.forum_threads(author_id);
create index idx_threads_last_post on public.forum_threads(last_post_at desc);
create index idx_posts_thread on public.forum_posts(thread_id);
create index idx_posts_author on public.forum_posts(author_id);
create index idx_reactions_post on public.forum_reactions(post_id);
create index idx_reports_status on public.forum_reports(status) where status = 'pending';
create index idx_dm_recipient on public.direct_messages(recipient_id, is_read);
create index idx_dm_conversation on public.direct_messages(sender_id, recipient_id);

-- ─── RLS Policies ───────────────────────────────────────────────────────────
alter table public.forum_categories enable row level security;
alter table public.forum_threads enable row level security;
alter table public.forum_posts enable row level security;
alter table public.forum_reactions enable row level security;
alter table public.forum_reports enable row level security;
alter table public.direct_messages enable row level security;
alter table public.user_blocks enable row level security;

-- Categories: anyone can read
create policy "Anyone can read categories" on forum_categories for select using (true);

-- Threads: anyone can read non-hidden, authors can manage own
create policy "Anyone can read visible threads" on forum_threads for select using (is_hidden = false);
create policy "Auth users can create threads" on forum_threads for insert with check (auth.uid() = author_id);
create policy "Authors can update own threads" on forum_threads for update using (auth.uid() = author_id);

-- Posts: anyone can read non-hidden, authors can manage own
create policy "Anyone can read visible posts" on forum_posts for select using (is_hidden = false);
create policy "Auth users can create posts" on forum_posts for insert with check (auth.uid() = author_id);
create policy "Authors can update own posts" on forum_posts for update using (auth.uid() = author_id);

-- Reactions: users manage own
create policy "Anyone can read reactions" on forum_reactions for select using (true);
create policy "Users can add reactions" on forum_reactions for insert with check (auth.uid() = user_id);
create policy "Users can remove own reactions" on forum_reactions for delete using (auth.uid() = user_id);

-- Reports: users can create, only see own
create policy "Users can report content" on forum_reports for insert with check (auth.uid() = reporter_id);
create policy "Users can see own reports" on forum_reports for select using (auth.uid() = reporter_id);

-- DMs: participants only
create policy "Users can read own DMs" on direct_messages for select
  using (auth.uid() = sender_id or auth.uid() = recipient_id);
create policy "Users can send DMs" on direct_messages for insert
  with check (auth.uid() = sender_id);
create policy "Recipients can mark read" on direct_messages for update
  using (auth.uid() = recipient_id);

-- Blocks: users manage own
create policy "Users can manage blocks" on user_blocks for all
  using (auth.uid() = blocker_id);

-- ─── Triggers ───────────────────────────────────────────────────────────────
create trigger set_forum_threads_updated_at before update on public.forum_threads
  for each row execute function public.set_updated_at();

create trigger set_forum_posts_updated_at before update on public.forum_posts
  for each row execute function public.set_updated_at();

-- ─── Seed default categories ────────────────────────────────────────────────
insert into public.forum_categories (name, description, emoji, sort_order, is_diagnosis_specific) values
  ('General Discussion', 'Open forum for all families', '💬', 1, false),
  ('Regional Centers', 'Questions about RC services and IPPs', '🏛️', 2, false),
  ('IEP & School', 'IEP meetings, school services, advocacy', '🏫', 3, false),
  ('Insurance & Benefits', 'Medi-Cal, CCS, SSI, insurance issues', '🏥', 4, false),
  ('Autism Spectrum', 'Families navigating ASD services', '🧩', 5, true),
  ('Down Syndrome', 'Support for DS families', '💛', 6, true),
  ('Cerebral Palsy', 'CP-specific resources and discussion', '💪', 7, true),
  ('Wins & Milestones', 'Celebrate your advocacy wins!', '🎉', 8, false),
  ('Resources & Tips', 'Share useful resources and strategies', '📚', 9, false);
-- Phase 6: Co-Parent Coordination schema
-- Multi-user family access with roles, invitations, and activity logging

-- ─── Family Members (multi-user access) ─────────────────────────────────────
create table public.family_members (
  id uuid primary key default gen_random_uuid(),
  family_id uuid references public.families(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  role text not null default 'member', -- 'admin', 'member', 'viewer'
  display_name text not null,
  joined_at timestamptz default now() not null,
  unique (family_id, user_id)
);

-- ─── Invitations ────────────────────────────────────────────────────────────
create table public.family_invitations (
  id uuid primary key default gen_random_uuid(),
  family_id uuid references public.families(id) on delete cascade not null,
  inviter_id uuid references auth.users(id) on delete cascade not null,
  invitee_email text not null,
  role text not null default 'member',
  status text not null default 'pending', -- 'pending', 'accepted', 'declined'
  token text not null default gen_random_uuid()::text,
  created_at timestamptz default now() not null,
  responded_at timestamptz
);

-- ─── Activity Log ───────────────────────────────────────────────────────────
create table public.activity_log (
  id uuid primary key default gen_random_uuid(),
  family_id uuid references public.families(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete set null,
  user_display_name text not null,
  action_type text not null, -- 'created_action', 'completed_action', 'added_appointment', 'uploaded_document', 'sent_message', etc.
  entity_type text, -- 'action', 'appointment', 'document', 'expense', etc.
  entity_id uuid,
  description text not null,
  created_at timestamptz default now() not null
);

-- ─── Indexes ────────────────────────────────────────────────────────────────
create index idx_family_members_family on public.family_members(family_id);
create index idx_family_members_user on public.family_members(user_id);
create index idx_invitations_family on public.family_invitations(family_id);
create index idx_invitations_email on public.family_invitations(invitee_email);
create index idx_invitations_token on public.family_invitations(token);
create index idx_activity_log_family on public.activity_log(family_id);
create index idx_activity_log_created on public.activity_log(created_at desc);

-- ─── RLS ────────────────────────────────────────────────────────────────────
alter table public.family_members enable row level security;
alter table public.family_invitations enable row level security;
alter table public.activity_log enable row level security;

-- Family members: access own family memberships
create policy "Users can see own family memberships" on family_members for select
  using (user_id = auth.uid() or family_id in (select family_id from family_members where user_id = auth.uid()));
create policy "Admins can manage family members" on family_members for all
  using (family_id in (select family_id from family_members where user_id = auth.uid() and role = 'admin'));

-- Invitations: inviters can manage, invitees can view/respond
create policy "Family admins can manage invitations" on family_invitations for all
  using (family_id in (select family_id from family_members where user_id = auth.uid() and role = 'admin'));

-- Activity log: family members can read
create policy "Family members can read activity" on activity_log for select
  using (family_id in (select family_id from family_members where user_id = auth.uid()));
create policy "Family members can write activity" on activity_log for insert
  with check (family_id in (select family_id from family_members where user_id = auth.uid()));
-- Phase 7: Provider Portal (B2B) schema
-- Provider profiles, family connections, messaging, and document access logging

-- ─── Provider Profiles ──────────────────────────────────────────────────────
create table public.provider_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null unique,
  name text not null,
  provider_type text not null,
  specialty text,
  organization text,
  npi_number text,
  credentials text,
  phone text,
  email text,
  address text,
  bio text,
  is_verified boolean default false,
  is_accepting_patients boolean default true,
  insurance_accepted text[] default '{}',
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- ─── Provider-Family Connections ────────────────────────────────────────────
create table public.provider_family_connections (
  id uuid primary key default gen_random_uuid(),
  provider_profile_id uuid references public.provider_profiles(id) on delete cascade not null,
  family_id uuid references public.families(id) on delete cascade not null,
  status text not null default 'pending', -- 'pending', 'approved', 'declined', 'revoked'
  requested_by text not null, -- 'provider' or 'family'
  created_at timestamptz default now() not null,
  responded_at timestamptz,
  unique (provider_profile_id, family_id)
);

-- ─── Provider-Family Messages ───────────────────────────────────────────────
create table public.provider_messages (
  id uuid primary key default gen_random_uuid(),
  connection_id uuid references public.provider_family_connections(id) on delete cascade not null,
  sender_type text not null, -- 'provider' or 'family'
  sender_id uuid references auth.users(id) on delete cascade not null,
  body text not null,
  is_read boolean default false,
  created_at timestamptz default now() not null
);

-- ─── Document Access Log (audit trail) ──────────────────────────────────────
create table public.document_access_logs (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.documents(id) on delete cascade not null,
  provider_profile_id uuid references public.provider_profiles(id) on delete cascade not null,
  accessed_at timestamptz default now() not null
);

-- ─── Indexes ────────────────────────────────────────────────────────────────
create index idx_provider_profiles_type on public.provider_profiles(provider_type);
create index idx_provider_profiles_org on public.provider_profiles(organization);
create index idx_provider_connections_provider on public.provider_family_connections(provider_profile_id);
create index idx_provider_connections_family on public.provider_family_connections(family_id);
create index idx_provider_messages_connection on public.provider_messages(connection_id);
create index idx_doc_access_doc on public.document_access_logs(document_id);

-- ─── RLS ────────────────────────────────────────────────────────────────────
alter table public.provider_profiles enable row level security;
alter table public.provider_family_connections enable row level security;
alter table public.provider_messages enable row level security;
alter table public.document_access_logs enable row level security;

-- Provider profiles: owners manage own, anyone can read for directory
create policy "Providers manage own profile" on provider_profiles for all
  using (user_id = auth.uid());
create policy "Anyone can read provider profiles" on provider_profiles for select using (true);

-- Connections: both parties can see
create policy "Connection participants can view" on provider_family_connections for select
  using (
    provider_profile_id in (select id from provider_profiles where user_id = auth.uid())
    or family_id in (select id from families where user_id = auth.uid())
  );
create policy "Either party can create connection" on provider_family_connections for insert
  with check (
    provider_profile_id in (select id from provider_profiles where user_id = auth.uid())
    or family_id in (select id from families where user_id = auth.uid())
  );
create policy "Either party can update connection" on provider_family_connections for update
  using (
    provider_profile_id in (select id from provider_profiles where user_id = auth.uid())
    or family_id in (select id from families where user_id = auth.uid())
  );

-- Messages: connection participants only
create policy "Connection participants can read messages" on provider_messages for select
  using (connection_id in (
    select id from provider_family_connections where
      provider_profile_id in (select id from provider_profiles where user_id = auth.uid())
      or family_id in (select id from families where user_id = auth.uid())
  ));
create policy "Connection participants can send messages" on provider_messages for insert
  with check (sender_id = auth.uid());

-- Document access logs: providers and document owners
create policy "Providers can log access" on document_access_logs for insert
  with check (provider_profile_id in (select id from provider_profiles where user_id = auth.uid()));
create policy "Document owners can view access logs" on document_access_logs for select
  using (document_id in (select id from documents where family_id in (select id from families where user_id = auth.uid())));

-- ─── Triggers ───────────────────────────────────────────────────────────────
create trigger set_provider_profiles_updated_at before update on public.provider_profiles
  for each row execute function public.set_updated_at();
-- Phase 8: Analytics & outcome tracking
-- Anonymous telemetry for action outcomes, KB helpfulness, and aggregate insights

-- ─── Analytics Events ───────────────────────────────────────────────────────
create table public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  family_id uuid references public.families(id) on delete set null,
  event_type text not null, -- 'action_outcome', 'draft_used', 'kb_helpful', 'kb_unhelpful', 'feature_used'
  event_data jsonb default '{}',
  -- Anonymized context for aggregation
  regional_center text,
  diagnosis_tags text[] default '{}',
  created_at timestamptz default now() not null
);

-- ─── Aggregate Insights (weekly computed) ───────────────────────────────────
create table public.aggregate_insights (
  id uuid primary key default gen_random_uuid(),
  insight_type text not null, -- 'rc_success_rate', 'action_type_success', 'trending_strategy'
  dimension text not null, -- e.g., 'ELARC', 'autism', 'fair_hearing'
  metric_value numeric not null,
  sample_size integer not null,
  period_start date not null,
  period_end date not null,
  metadata jsonb default '{}',
  computed_at timestamptz default now() not null
);

-- ─── Indexes ────────────────────────────────────────────────────────────────
create index idx_analytics_type on public.analytics_events(event_type);
create index idx_analytics_rc on public.analytics_events(regional_center);
create index idx_analytics_created on public.analytics_events(created_at desc);
create index idx_insights_type on public.aggregate_insights(insight_type, dimension);
create index idx_insights_period on public.aggregate_insights(period_end desc);

-- ─── RLS ────────────────────────────────────────────────────────────────────
alter table public.analytics_events enable row level security;
alter table public.aggregate_insights enable row level security;

-- Events: users can write own, service role reads all
create policy "Users can log own events" on analytics_events for insert
  with check (family_id in (select id from families where user_id = auth.uid()));

-- Insights: anyone authenticated can read (they're anonymized/aggregated)
create policy "Authenticated users can read insights" on aggregate_insights for select
  using (auth.uid() is not null);
-- Phase 10: Resources, Guides & Blog schema

-- ─── Resources / Guides ─────────────────────────────────────────────────────
create table public.resources (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  category text not null, -- 'getting_started', 'regional_center', 'iep', 'insurance', 'legal', 'transitions'
  tags text[] default '{}',
  difficulty_level text default 'beginner', -- 'beginner', 'intermediate', 'advanced'
  estimated_read_time integer default 5, -- minutes
  related_kb_ids text[] default '{}',
  is_published boolean default true,
  published_at timestamptz default now(),
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- ─── Blog Posts ─────────────────────────────────────────────────────────────
create table public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  excerpt text,
  body text not null,
  author text not null default 'Waypoint Team',
  category text not null, -- 'advocacy', 'news', 'guides', 'stories', 'updates'
  tags text[] default '{}',
  featured_image_url text,
  is_featured boolean default false,
  is_published boolean default false,
  published_at timestamptz,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- ─── Indexes ────────────────────────────────────────────────────────────────
create index idx_resources_category on public.resources(category);
create index idx_resources_published on public.resources(is_published, published_at desc);
create index idx_blog_category on public.blog_posts(category);
create index idx_blog_published on public.blog_posts(is_published, published_at desc);
create index idx_blog_featured on public.blog_posts(is_featured) where is_featured = true;

-- ─── RLS ────────────────────────────────────────────────────────────────────
alter table public.resources enable row level security;
alter table public.blog_posts enable row level security;

-- All authenticated users can read published content
create policy "Anyone can read published resources" on resources for select
  using (is_published = true);
create policy "Anyone can read published blog posts" on blog_posts for select
  using (is_published = true);

-- ─── Triggers ───────────────────────────────────────────────────────────────
create trigger set_resources_updated_at before update on public.resources
  for each row execute function public.set_updated_at();
create trigger set_blog_posts_updated_at before update on public.blog_posts
  for each row execute function public.set_updated_at();
