/**
 * Generates supabase/seed/kb_seed.sql from the curated KB articles JSON.
 * The output is a paste-ready SQL script for the Supabase SQL editor —
 * no embeddings required (retrieval uses full-text search, migration 011).
 *
 * Usage: node scripts/generate-kb-seed.js
 */
const fs = require('fs');
const path = require('path');

const KB_FILE = path.resolve(
  __dirname,
  '../../Waypoint-Lite-KB-Articles-ENHANCED-AI-SCHEMA-Feb2026.json'
);
const OUT_FILE = path.resolve(__dirname, '../supabase/seed/kb_seed.sql');

// Same parsing rules as scripts/ingest-kb.ts
function parseArticle(article) {
  const titleMatch = article.code_title.match(/^([A-Z]+-\d+):\s*(.+)$/);
  const code = titleMatch?.[1] ?? article.code_title;
  const title = titleMatch?.[2] ?? article.code_title;

  const lines = article.body.split('\n');
  const metaLine = lines[0] ?? '';
  const metaMatch = metaLine.match(
    /Category:\s*([^|]+)\|\s*Subcategory:\s*([^|]+)\|\s*Source:\s*(.+)/
  );

  const category = metaMatch?.[1]?.trim() ?? 'unknown';
  const subcategory = metaMatch?.[2]?.trim() ?? 'unknown';
  const sourceRef = metaMatch?.[3]?.trim() ?? '';
  const contentStart = metaMatch ? 2 : 0;
  const content = lines.slice(contentStart).join('\n').trim();

  return {
    code,
    title,
    category,
    subcategory,
    sourceRef,
    content,
    lastReviewed: article.last_reviewed,
  };
}

// Dollar-quote a string, picking a tag that never appears in the content
function dollarQuote(text) {
  let tag = 'kb';
  while (text.includes(`$${tag}$`)) tag += 'x';
  return `$${tag}$${text}$${tag}$`;
}

const kb = JSON.parse(fs.readFileSync(KB_FILE, 'utf-8'));
const rows = kb.articles.map((a) => {
  const p = parseArticle(a);
  const content = `${p.title}\n\n${p.content}`;
  const source = p.category.replace(/-/g, '_');
  const metadata = {
    code: p.code,
    title: p.title,
    category: p.category,
    subcategory: p.subcategory,
    source_ref: p.sourceRef,
    last_reviewed: p.lastReviewed,
  };
  return `insert into public.knowledge_embeddings (content, source, section, metadata) values (${dollarQuote(content)}, ${dollarQuote(source)}, ${dollarQuote(p.code)}, ${dollarQuote(JSON.stringify(metadata))}::jsonb);`;
});

const sql = [
  '-- Waypoint KB seed — generated by scripts/generate-kb-seed.js',
  `-- ${rows.length} curated articles from ${path.basename(KB_FILE)}`,
  '-- Paste into the Supabase SQL editor AFTER running migration 011.',
  '',
  'begin;',
  '',
  '-- Replace any previous seed (idempotent re-runs)',
  'delete from public.knowledge_embeddings;',
  '',
  ...rows,
  '',
  'commit;',
  '',
].join('\n');

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, sql);
console.log(`Wrote ${OUT_FILE} (${rows.length} articles, ${(sql.length / 1024).toFixed(0)} KB)`);
