-- 004: Actions table for Action Plan & Tracker (Sprint 3)
-- Stores actionable next steps generated by AI Navigator or created manually

create table public.actions (
  id uuid primary key default gen_random_uuid(),
  family_id uuid references public.families(id) on delete cascade not null,
  child_id uuid references public.children(id) on delete set null,
  chat_session_id uuid references public.chat_sessions(id) on delete set null,

  -- Core fields
  title text not null,
  description text,
  category text not null default 'general',
    -- 'regional_center', 'iep', 'insurance', 'benefits', 'medical', 'legal', 'general'
  priority text not null default 'medium',
    -- 'urgent', 'high', 'medium', 'low'

  -- Status management (4 states per Sprint 3 spec)
  status text not null default 'not_started'
    check (status in ('not_started', 'in_progress', 'completed', 'dismissed')),

  -- Scripts / guidance
  script text,           -- Pre-written script (e.g., "call your RC and say...")
  steps jsonb,           -- Ordered checklist: [{step: "...", done: bool}]
  kb_article_ids text[], -- Links to relevant KB articles (e.g., ['RC-001', 'RC-003'])

  -- Timelines
  due_date date,
  deadline_warning_days integer default 7,
  completed_at timestamptz,
  dismissed_at timestamptz,
  dismissed_reason text,

  -- Source tracking
  source text not null default 'manual',
    -- 'ai_navigator' (saved from chat), 'manual' (user-created), 'system' (auto-generated)
  source_message_id uuid, -- If saved from chat, the specific message ID

  -- Follow-up
  follow_up_date date,
  follow_up_note text,
  reminder_sent boolean default false,

  -- Offline sync
  local_id text,           -- Client-side ID for offline-created actions
  synced_at timestamptz,   -- Last successful sync timestamp
  version integer default 1, -- Optimistic concurrency control

  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Indexes
create index idx_actions_family_id on public.actions(family_id);
create index idx_actions_child_id on public.actions(child_id);
create index idx_actions_status on public.actions(status);
create index idx_actions_due_date on public.actions(due_date);
create index idx_actions_category on public.actions(category);
create index idx_actions_local_id on public.actions(local_id) where local_id is not null;

-- Updated_at trigger
create trigger set_updated_at before update on public.actions
  for each row execute function public.handle_updated_at();

-- RLS policies (matches pattern from 002)
alter table public.actions enable row level security;

create policy "Users can manage their own actions"
  on public.actions for all
  using (family_id in (select id from public.families where user_id = auth.uid()))
  with check (family_id in (select id from public.families where user_id = auth.uid()));

-- Analytics view: action completion stats per family
create or replace view public.action_stats as
select
  family_id,
  count(*) as total_actions,
  count(*) filter (where status = 'completed') as completed_count,
  count(*) filter (where status = 'in_progress') as in_progress_count,
  count(*) filter (where status = 'not_started') as not_started_count,
  count(*) filter (where status = 'dismissed') as dismissed_count,
  round(
    count(*) filter (where status = 'completed')::numeric
    / nullif(count(*) filter (where status != 'dismissed'), 0) * 100,
    1
  ) as completion_rate,
  avg(
    extract(epoch from (completed_at - created_at)) / 86400
  ) filter (where status = 'completed') as avg_days_to_complete
from public.actions
group by family_id;
